export const SET_INGREDIENTS = 'SET_INGREDIENTS'
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED'
export const CHANGE_INGREDIENT = 'CHANGE_INGREDIENT'

export const AJAX_START = 'AJAX_START'
export const AJAX_FAIL = 'AJAX_FAIL'
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS'
export const PURCHASE_INIT = 'PURCHASE_INIT'

export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const SET_AUTH_REDIRECT = 'SET_AUTH_REDIRECT'